services:
  tor:
    build: ./tor
    deploy:
      mode: replicated
      replicas: ${rcount}
    restart: always
    configs:
      - source: torconf
        target: /etc/tor/torrc
    healthcheck:
      test: ["CMD-SHELL", "curl -fx socks5h://localhost:9050 'https://check.torproject.org/'", "||", "exit 1"]
      # Когда совершить первую проверку
      start_period: 60s
      # Через сколько секунд повторить проверку
      interval: 15s
      # Сколько времени даётся на саму проверку, или сбой
      timeout: 3s
      # Сколько попыток сделать
      retries: 3
  privoxy:
    build: ./privoxy
    deploy:
      mode: replicated
      replicas: ${rcount}
    restart: always
    depends_on:
      tor:
        condition: service_healthy
        restart: true
  squid:
    build: ./squid
    restart: always
#  bbulder:

configs:
  torconf:
    file: ./cfg/tor
