services:
  tor:
    build: ./tor
    deploy:
      mode: replicated
      replicas: ${rcount}
    restart: always
    configs:
      - source: torconf
        target: /etc/tor/torrc
    healthcheck:
      test: ["CMD-SHELL", "curl -sx socks5h://localhost:9050 'https://check.torproject.org/'", "|", "grep -qm1 Congratulations"]
      start_period: 20s
      interval: 15s
      timeout: 7s
      retries: 3
  privoxy:
    build: ./privoxy
    deploy:
      mode: replicated
      replicas: ${rcount}
    restart: always
    depends_on:
      tor:
        condition: service_healthy
        restart: true
  squid:
    build: ./squid
    restart: always
#  bbulder:

configs:
  torconf:
    file: ./cfg/tor
