FROM alpine:latest
LABEL maintainer="alisterosenheim@outlook.com"
RUN apk --no-cache add python3 \
                       openvpn
RUN alias python=python3
COPY mgr mgr
EXPOSE 80
CMD [ "python", "-u", "mgr/main.py" ]