FROM alpine:latest
LABEL maintainer="alisterosenheim@outlook.com"
RUN apk --no-cache add tzdata \
                       curl \
                       make \
                       go \
                       tor
COPY lyrebird lyrebird
RUN make build -C ./lyrebird/ && \ 
    cp ./lyrebird/lyrebird /usr/local/bin && \
    rm -rf /lyrebird/
RUN apk del make go
EXPOSE 9050
CMD ["tor"]